/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Vista;

/**
 *
 * @author OMCG1
 */
import Modelo.Conexion;
import Modelo.LoginDAO;
import Modelo.login;
import com.mysql.cj.exceptions.StatementIsClosedException;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.SQLSyntaxErrorException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import sun.tools.jstat.SyntaxException;

public class Login extends javax.swing.JFrame {

    login lg = new login();
    LoginDAO login = new LoginDAO();

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtCorreo.setText("admin");
        txtPass.setText("admin");
    }

    public void validar() {
        String correo = txtCorreo.getText();
        String pass = String.valueOf(txtPass.getPassword());
        if (!"".equals(correo) || !"".equals(pass)) {

            lg = login.log(correo, pass);
            if (lg.getCorreo() != null && lg.getPass() != null) {
                Sistema sis = new Sistema(lg);
                sis.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Credenciales invádilas.");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Iniciar sesión", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(82, 13, 27)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuario_1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Correo electrónico:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Contraseña:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 226, 30));
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 226, 30));

        btnIniciar.setBackground(new java.awt.Color(102, 0, 51));
        btnIniciar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Ingresar");
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 93, 34));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 280, 370));

        jPanel1.setBackground(new java.awt.Color(82, 13, 27));
        jPanel1.setForeground(new java.awt.Color(169, 26, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fruteria.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, 160));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("EL FRUTECNO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, -1));

        jButton1.setBackground(new java.awt.Color(102, 0, 51));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ingresar a SII");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 260, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fruteria y tienda de abarrotes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 170, 20));

        jButton2.setBackground(new java.awt.Color(102, 0, 51));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Crear base de datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 260, 40));

        jButton3.setBackground(new java.awt.Color(102, 0, 51));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Eliminar base de datos");
        jButton3.setPreferredSize(new java.awt.Dimension(160, 20));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 260, 40));

        jButton4.setBackground(new java.awt.Color(57, 0, 0));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Salir");
        jButton4.setPreferredSize(new java.awt.Dimension(160, 20));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/kisspng-fruit-supermarket-vegetable-auglis-supermarket-shelf-water-5aa275ca7f6719.0857573115205964265219.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 550, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        try {
            validar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Base de datos inexistente.");

        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://siit.itdurango.edu.mx/sistema/modulos/alu/"));
        } catch (IOException | URISyntaxException e1) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/", "root", "");
            Statement stmt = con.createStatement();
            stmt.execute("create database sistemafrutecno");
            JOptionPane.showMessageDialog(null, "Base de datos creada exitosamente.");
        } catch (ClassNotFoundException error) {
            JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos: " + error);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Base de datos ya existente.");
        }

        try {
            String clientes = "CREATE TABLE clientes("
                    + "id INT PRIMARY KEY AUTO_INCREMENT,"
                    + "dni INT(10) NOT NULL,"
                    + "nombre VARCHAR(200) NOT NULL,"
                    + "telefono VARCHAR(200) NOT NULL,"
                    + "direccion VARCHAR(200) NOT NULL"
                    + ")";
            String config = "CREATE TABLE config("
                    + "id INT PRIMARY KEY AUTO_INCREMENT,"
                    + "ruc VARCHAR(50) NOT NULL DEFAULT 'SIN ASIGNAR',"
                    + "nombre VARCHAR(200) NOT NULL DEFAULT 'SIN ASIGNAR',"
                    + "telefono VARCHAR(50) NOT NULL DEFAULT '0',"
                    + "direccion TEXT(200) NOT NULL DEFAULT 'SIN ASIGNAR',"
                    + "mensaje VARCHAR(200) NOT NULL DEFAULT 'SIN ASIGNAR'"
                    + ")";
            String productos = "CREATE TABLE productos("
                    + "id INT PRIMARY KEY AUTO_INCREMENT,"
                    + "codigo VARCHAR(200) NOT NULL,"
                    + "nombre TEXT NOT NULL,"
                    + "proveedor INT NOT NULL,"
                    + "INDEX proveedor (proveedor),"
                    + "stock INT,"
                    + "precio DECIMAL(15,2) NOT NULL"
                    + ")";
            String detalle = "CREATE TABLE detalle("
                    + "id INT PRIMARY KEY AUTO_INCREMENT,"
                    + "id_pro INT NOT NULL, "
                    + "cantidad INT NOT NULL,"
                    + "precio DECIMAL(15,2) NOT NULL,"
                    + "INDEX id_pro (id_pro),"
                    + "id_venta INT NOT NULL, "
                    + "INDEX id_venta (id_venta),"
                    + "FOREIGN KEY (id_pro) REFERENCES productos(id)"
                    + ")";
            String proveedor = "CREATE TABLE proveedor("
                    + "id INT PRIMARY KEY AUTO_INCREMENT,"
                    + "ruc VARCHAR (50) NOT NULL,"
                    + "nombre VARCHAR (200) NOT NULL,"
                    + "telefono VARCHAR (50) NOT NULL,"
                    + "direccion VARCHAR (200) NOT NULL"
                    + ")";
            String usuarios = "CREATE TABLE usuarios("
                    + "id INT PRIMARY KEY AUTO_INCREMENT,"
                    + "nombre VARCHAR (200) NOT NULL,"
                    + "correo VARCHAR (200) NOT NULL,"
                    + "pass VARCHAR (200) NOT NULL,"
                    + "rol VARCHAR (50) NOT NULL"
                    + ")";
            String ventas = "CREATE TABLE ventas("
                    + "id INT PRIMARY KEY AUTO_INCREMENT,"
                    + "cliente INT NOT NULL,"
                    + "INDEX cliente (cliente),"
                    + "FOREIGN KEY (cliente) REFERENCES clientes(id),"
                    + "vendedor VARCHAR (200) NOT NULL,"
                    + "total DECIMAL (15,2) NOT NULL,"
                    + "fecha VARCHAR (50) NOT NULL"
                    + ")";
            String config_aplicar = "INSERT INTO config (id, ruc, nombre, telefono, direccion, mensaje) VALUES "
                    + "(1, 'IDE990920KB8', 'INSTITUTO TECNOLOGICO DE DURANGO', '+52 6188290900', 'Blvd. Felipe Pescador 1830 Ote. Col. Nueva Vizcaya. Durango, Dgo. México C.P. 34080.', '!Gloria al tecno!')";
            String usuarios_aplicar = "INSERT INTO usuarios (id, nombre, correo, pass, rol) VALUES "
                    + "(1, 'admin', 'admin', 'admin', 'Administrador')";

            Conexion obj = new Conexion();
            obj.getConnection();
            Statement st;
            st = (Statement) obj.con.createStatement();
            st.executeUpdate(clientes);
            st.executeUpdate(config);
            st.executeUpdate(productos);
            st.executeUpdate(detalle);
            st.executeUpdate(proveedor);
            st.executeUpdate(usuarios);
            st.executeUpdate(ventas);
            st.executeUpdate(config_aplicar);
            st.executeUpdate(usuarios_aplicar);

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Tablas ya existentes.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/", "root", "");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("drop database sistemafrutecno");
            JOptionPane.showMessageDialog(null, "Base de datos eliminada exitosamente.");
        } catch (ClassNotFoundException error) {
            JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos: " + error);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Base de datos inexistente.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
